version: '3'
services:
  port_stalker:
    build: app
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - "./config_flask.py-example:/app/pril/config.py"
  redis:
    image: redis
    restart: always
  lady_of_the_winds:
    build: client_React
    restart: always
    ports:
      - "8030:3000"
    volumes:
      - "./config_react.json-example:/client_React/src/config.json"
  noda:
    image:
