version: '3'
services:
  darkniter_flask:
    build: app
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - "./config.py:/app/pril/config.py"
  redis:
    container_name: redis
    image: redis
    restart: always